---
title: "QC Report"
date: "Updated: `r format(Sys.time())`"
output:
      html_document:
      highlight: tango
        # number_sections: yes
        # toc: yes
        # toc_depth: 2
        # toc_float: yes
params:
  loo.key: NA
  experiment: NA
  bcl.dir: NA
  amp.match.summary: NA
  seq.metrics: NA
  results: NA
   results.summary: NA
  dlong: NA
  dwide: NA
  dsummary.reduced: NA
---

<!--
read_quality: NA
  seq_cont_per_cycle: NA
  read_freq_plot: NA
  base_calls_plot: NA
  -->


# `r paste("Experiment:", params$experiment)`
# `r paste(params$bcl.dir)`


```{r include=FALSE}
library(ggplot2)
library(knitr)
library(DT)
# library(ggpubr)
```
## Results Summary
```{r echo=FALSE}
    params$results.summary %>% 
    kable()
```


## Sequencer metrics
```{r echo=FALSE}
params$seq.metrics %>%
kable()
```

## Alignment summary
```{r echo=FALSE}
data.frame(num_reads = params$amp.match.summary) %>% 
kable()
```

## Plate maps (384)
```{r echo=FALSE, fig.height=10, fig.width=12}
params$dlong %>% 
ggplot(aes(x=Col, y=Row, fill=log10(Count))) + 
  geom_raster() +
  coord_equal() +
  facet_grid(amplicon~Plate_384+Plate_ID) +
  scale_fill_viridis_c(option = 'plasma')+ggtitle(params$experiment)
```

## Swabseq Calls (384)
```{r echo=FALSE, fig.height=10, fig.width=12}
params$dwide %>% 
ggplot(aes(x=Col, y=Row, fill=SARS_COV_2_Detected)) + 
  geom_raster() +
  coord_equal() +
  facet_grid(~Plate_384+Plate_ID) +
  #scale_fill_viridis_c(option = 'plasma')+
  ggtitle(params$experiment)
```

## S2 and S2 spike QC (384)
```{r echo=FALSE, fig.height=10, fig.width=12}
params$dwide %>% 
ggplot(aes(x=Col, y=Row, fill=Stotal>500)) + 
  geom_raster() +
  coord_equal() +
  facet_grid(~Plate_384+Plate_ID) +
  #scale_fill_viridis_c(option = 'plasma')+
  ggtitle(params$experiment)
```

## RPP30 QC (384)
```{r echo=FALSE, fig.height=10, fig.width=12}
params$dwide %>% 
ggplot(aes(x=Col, y=Row, fill=RPP30_Detected)) + 
  geom_raster() +
  coord_equal() +
  facet_grid(~Plate_384+Plate_ID) +
  #scale_fill_viridis_c(option = 'plasma')+
  ggtitle(params$experiment)
```

## Plate maps (96)
```{r echo=FALSE, fig.height=10, fig.width=12}
psplit=split(params$dlong, params$dlong$Plate_384)
lapply(psplit, function(x) {
           x%>%
ggplot(aes(x=Col96, y=Row96, fill=log10(Count))) + 
  geom_raster() +
  coord_equal() +
  facet_grid(amplicon~Plate_384+Plate_ID+quadrant_96) +
  scale_fill_viridis_c(option = 'plasma')+ggtitle(params$experiment)
})
```

## S2 and S2 spike QC (96)
```{r echo=FALSE, fig.height=10, fig.width=12}
psplit=split(params$dwide, params$dwide$Plate_384)
lapply(psplit, function(x) {
           x%>%
ggplot(aes(x=Col96, y=Row96, fill=Stotal>500)) + 
  geom_raster() +
  coord_equal() +
  facet_grid(~Plate_384+Plate_ID+quadrant_96) +
  #scale_fill_viridis_c(option = 'plasma')+
  ggtitle(params$experiment)
})
```

## RPP30 QC (96)
```{r echo=FALSE, fig.height=10, fig.width=12}
psplit=split(params$dwide, params$dwide$Plate_384)
lapply(psplit, function(x) {
           x%>%
ggplot(aes(x=Col96, y=Row96, fill=RPP30_Detected)) + 
  geom_raster() +
  coord_equal() +
  facet_grid(~Plate_384+Plate_ID+quadrant_96) +
  #scale_fill_viridis_c(option = 'plasma')+
  ggtitle(params$experiment)
})
```
## Swabseq Calls (96)
```{r echo=FALSE, fig.height=10, fig.width=12}
psplit=split(params$dwide, params$dwide$Plate_384)
lapply(psplit, function(x) {
           x%>%
ggplot(aes(x=Col96, y=Row96, fill=SARS_COV_2_Detected)) + 
  geom_raster() +
  coord_equal() +
  facet_grid(~Plate_384+Plate_ID+quadrant_96) +
  #scale_fill_viridis_c(option = 'plasma')+
  ggtitle(params$experiment)
})
```

## Leave Out Tubes QC (96)
```{r echo=FALSE, fig.height=10, fig.width=12}
p=params$dwide
p$id_tubes=p$virus_identity %in% params$loo.key$ID

psplit=split(p, p$Plate_384)
lapply(psplit, function(x) {
           x%>%
ggplot(aes(x=Col96, y=Row96, fill=id_tubes)) + 
  geom_raster() +
  coord_equal() +
  facet_grid(~Plate_384+Plate_ID+quadrant_96) +
  #scale_fill_viridis_c(option = 'plasma')+
  ggtitle(params$experiment)
})
```
<!--
## Sequence quality per base/cycle
```{r echo=FALSE}
eval(params$read_quality)
```

## Sequence content per base/cycle

```{r echo=FALSE}
eval(params$seq_cont_per_cycle)
```

## Base calls per cycle

```{r echo=FALSE}
eval(params$base_calls_plot)
```


## Read frequency plot

```{r echo=FALSE}
eval(params$read_freq_plot)
```
-->

## Results
```{r echo=FALSE}
params$dsummary.reduced %>% datatable(options=list(pageLength=25,order=list(list(9,'desc'))))
```



